function c2r = extractC2forImages(imgs,c2args)
% function c2r = extractC2forDir(imageDir,ext,c2args)
%
% extract c2 activations for a list of images

numImgs = length(imgs);

for imgnum = 1:numImgs
    printProgress(imgnum,numImgs,50);
    c2r(:,imgnum) = extractC2forimage(c2args.filters,...
                                      c2args.filterSizes,...
                                      c2args.c1SpaceSS,...
                                      c2args.c1ScaleSS,...
                                      c2args.c1OL,...
                                      c2args.cPatches,...
                                      imgs{imgnum},...
                                      c2args.nPatchSizes);
end